# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20160512_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='havetotask',
            old_name='due_date',
            new_name='hard_due_date',
        ),
        migrations.RenameField(
            model_name='havetotask',
            old_name='should_be_date',
            new_name='soft_due_date',
        ),
        migrations.AddField(
            model_name='havetotask',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
