# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20160516_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='havetotask',
            name='task_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
